name: Push to Koji using Teleport

on:
  push:
    branches: [ "um36" ]

jobs:
  build:
    uses: Ultramarine-Linux/github-actions/.github/workflows/rpm.yml@main
    with:
      name: "umpkg"
    secrets:
      teleportIdentity: ${{ secrets.TELEPORT_IDENTITY }}
